"""
Revision script template for Alembic.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8df0ea5608fa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "line_groups",
        sa.Column("id", sa.Integer(), nullable=False, comment="主鍵 ID"),
        sa.Column("uniid", sa.String(length=64), nullable=False, comment="群唯一碼"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="群名"),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="狀態 (active, inactive)",
        ),
        sa.Column("type", sa.String(length=32), nullable=False, comment="群組類別"),
        sa.Column("member_count", sa.Integer(), nullable=False, comment="群組成員數"),
        sa.Column(
            "message_count",
            sa.Integer(),
            nullable=False,
            comment="已匯入或紀錄的訊息總數",
        ),
        sa.Column(
            "vector_chunks_count",
            sa.Integer(),
            nullable=False,
            comment="與群組相關的向量切塊數量",
        ),
        sa.Column(
            "google_drive_folder",
            sa.String(length=64),
            nullable=True,
            comment="google drive的LINE群根目錄",
        ),
        sa.Column(
            "google_file_folder",
            sa.String(length=64),
            nullable=True,
            comment="google drive的LINE群檔案根目錄",
        ),
        sa.Column(
            "google_image_folder",
            sa.String(length=64),
            nullable=True,
            comment="google drive的LINE群圖片根目錄",
        ),
        sa.Column(
            "google_video_folder",
            sa.String(length=64),
            nullable=True,
            comment="google drive的LINE群影像根目錄",
        ),
        sa.Column(
            "available_counts", sa.Integer(), nullable=False, comment="可使用次數"
        ),
        sa.Column(
            "expiration_at", sa.String(length=32), nullable=True, comment="截止時間"
        ),
        sa.Column(
            "chunk_summary_prompt",
            sa.Text(),
            nullable=True,
            comment="訊息塊摘要的提示詞",
        ),
        sa.Column(
            "daily_summary_prompt",
            sa.Text(),
            nullable=True,
            comment="訊息日摘要的提示詞",
        ),
        sa.Column(
            "analyze_intent_prompt",
            sa.Text(),
            nullable=True,
            comment="使用者提問意圖的提示詞",
        ),
        sa.Column(
            "synthesize_answer_prompt",
            sa.Text(),
            nullable=True,
            comment="答案總結的提示詞",
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="建立時間"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新時間"
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="軟刪除時間",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_line_groups_status"), "line_groups", ["status"], unique=False
    )
    op.create_index(
        "ix_line_groups_status_created_at",
        "line_groups",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_line_groups_uniid"), "line_groups", ["uniid"], unique=False
    )
    op.create_table(
        "line_messages",
        sa.Column("id", sa.Integer(), nullable=False, comment="主鍵 ID"),
        sa.Column("group_id", sa.Integer(), nullable=False, comment="所屬群組 ID"),
        sa.Column(
            "message_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="訊息時間",
        ),
        sa.Column(
            "message_uid",
            sa.String(length=32),
            nullable=True,
            comment="所屬LINE訊息UID",
        ),
        sa.Column(
            "reply_message_uid",
            sa.String(length=32),
            nullable=True,
            comment="所屬LINE訊息回覆UID",
        ),
        sa.Column(
            "user_name", sa.String(length=64), nullable=True, comment="發送者名稱"
        ),
        sa.Column(
            "user_uid", sa.String(length=64), nullable=True, comment="發送者 UID"
        ),
        sa.Column("message_content", sa.Text(), nullable=True, comment="訊息原文"),
        sa.Column("sticker", sa.String(length=200), nullable=True, comment="貼圖"),
        sa.Column(
            "link_url", sa.String(length=2048), nullable=True, comment="檔案連結"
        ),
        sa.Column("link_description", sa.Text(), nullable=True, comment="描述"),
        sa.Column(
            "message_description", sa.Text(), nullable=True, comment="處理後摘要"
        ),
        sa.Column(
            "chunk_id", sa.String(length=100), nullable=True, comment="向量切塊 ID"
        ),
        sa.Column(
            "vector_processed", sa.Boolean(), nullable=False, comment="已送入向量化處理"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="建立時間"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新時間"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["line_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_line_messages_chunk_id"), "line_messages", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_line_messages_group_id"), "line_messages", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_line_messages_message_time"),
        "line_messages",
        ["message_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_line_messages_message_time"), table_name="line_messages")
    op.drop_index(op.f("ix_line_messages_group_id"), table_name="line_messages")
    op.drop_index(op.f("ix_line_messages_chunk_id"), table_name="line_messages")
    op.drop_table("line_messages")
    op.drop_index(op.f("ix_line_groups_uniid"), table_name="line_groups")
    op.drop_index("ix_line_groups_status_created_at", table_name="line_groups")
    op.drop_index(op.f("ix_line_groups_status"), table_name="line_groups")
    op.drop_table("line_groups")
    # ### end Alembic commands ###
