"""
Revision script template for Alembic.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "997dfb041f62"
down_revision = 'd7f2600cb958'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_groups', sa.Column('user_id', sa.Integer(), nullable=True, comment='所屬使用者 ID'))
    op.alter_column('line_groups', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_comment='狀態 (active, inactive)',
               existing_nullable=False)
    op.create_index(op.f('ix_line_groups_user_id'), 'line_groups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_groups_user_id'), table_name='line_groups')
    op.alter_column('line_groups', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_comment='狀態 (active, inactive)',
               existing_nullable=False)
    op.drop_column('line_groups', 'user_id')
    # ### end Alembic commands ###
