"""
Revision script template for Alembic.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b6c9ed72eb2"
down_revision = 'a3f46afbb299'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_summary_tags',
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵 ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='所屬群組 ID'),
    sa.Column('summary_time', sa.DateTime(timezone=True), nullable=True, comment='摘要時間'),
    sa.Column('chunk_summary', sa.Boolean(), nullable=False, comment='是否段摘要已完成'),
    sa.Column('daily_summary', sa.Boolean(), nullable=False, comment='是否日摘要已完成'),
    sa.Column('chunk_current_retry', sa.Integer(), nullable=False, comment='段摘要目前重試次數'),
    sa.Column('daily_current_retry', sa.Integer(), nullable=False, comment='日摘要目前重試次數'),
    sa.Column('chunk_max_retry', sa.Integer(), nullable=False, comment='段摘要最大重試次數'),
    sa.Column('daily_max_retry', sa.Integer(), nullable=False, comment='日摘要最大重試次數'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['group_id'], ['line_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group', 'message_summary_tags', ['group_id'], unique=False)
    op.create_index(op.f('ix_message_summary_tags_group_id'), 'message_summary_tags', ['group_id'], unique=False)
    op.create_index(op.f('ix_message_summary_tags_updated_at'), 'message_summary_tags', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_summary_tags_updated_at'), table_name='message_summary_tags')
    op.drop_index(op.f('ix_message_summary_tags_group_id'), table_name='message_summary_tags')
    op.drop_index('idx_group', table_name='message_summary_tags')
    op.drop_table('message_summary_tags')
    # ### end Alembic commands ###
