"""
Revision script template for Alembic.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3f46afbb299"
down_revision = '86ee22964e7f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_message_summaries',
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵 ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='所屬群組 ID'),
    sa.Column('message_time', sa.DateTime(timezone=True), nullable=True, comment='訊息時間'),
    sa.Column('message_description', sa.Text(), nullable=True, comment='處理後摘要'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['group_id'], ['line_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group_message_time', 'group_message_summaries', ['group_id'], unique=False)
    op.create_index('idx_message_time', 'group_message_summaries', ['message_time'], unique=False)
    op.create_index(op.f('ix_group_message_summaries_group_id'), 'group_message_summaries', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_message_summaries_message_time'), 'group_message_summaries', ['message_time'], unique=False)
    op.create_index(op.f('ix_group_message_summaries_updated_at'), 'group_message_summaries', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_message_summaries_updated_at'), table_name='group_message_summaries')
    op.drop_index(op.f('ix_group_message_summaries_message_time'), table_name='group_message_summaries')
    op.drop_index(op.f('ix_group_message_summaries_group_id'), table_name='group_message_summaries')
    op.drop_index('idx_message_time', table_name='group_message_summaries')
    op.drop_index('idx_group_message_time', table_name='group_message_summaries')
    op.drop_table('group_message_summaries')
    # ### end Alembic commands ###
