"""
Revision script template for Alembic.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7f2600cb958"
down_revision = 'e6655bf00fc0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_message_summaries',
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵 ID'),
    sa.Column('chunk_id', sa.String(length=100), nullable=False, comment='向量切塊ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='所屬群組 ID'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='片段開始時間'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='片段結束時間'),
    sa.Column('message_ids', sa.String(length=1024), nullable=False, comment='訊息 id 列表（如1,3,12,16）'),
    sa.Column('message_content', sa.Text(), nullable=True, comment='處理前訊息'),
    sa.Column('message_summary', sa.Text(), nullable=True, comment='處理後摘要'),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=True, comment='Qdrant point id'),
    sa.Column('embedding', sa.JSON(), nullable=True, comment='Embedding vector'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['group_id'], ['line_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group_time', 'chunk_message_summaries', ['group_id'], unique=False)
    op.create_index('idx_group_time_range', 'chunk_message_summaries', ['group_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_chunk_message_summaries_group_id'), 'chunk_message_summaries', ['group_id'], unique=False)
    op.create_index(op.f('ix_chunk_message_summaries_qdrant_point_id'), 'chunk_message_summaries', ['qdrant_point_id'], unique=False)
    op.create_index(op.f('ix_chunk_message_summaries_updated_at'), 'chunk_message_summaries', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_message_summaries_updated_at'), table_name='chunk_message_summaries')
    op.drop_index(op.f('ix_chunk_message_summaries_qdrant_point_id'), table_name='chunk_message_summaries')
    op.drop_index(op.f('ix_chunk_message_summaries_group_id'), table_name='chunk_message_summaries')
    op.drop_index('idx_group_time_range', table_name='chunk_message_summaries')
    op.drop_index('idx_group_time', table_name='chunk_message_summaries')
    op.drop_table('chunk_message_summaries')
    # ### end Alembic commands ###
